# Generated by Django 5.2.11 on 2026-09-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipeds_unitid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(default='US', max_length=2)),
                ('ownership', models.CharField(max_length=32)),
                ('official_website', models.URLField(blank=True)),
                ('operating_status', models.CharField(max_length=32)),
                ('bachelors_granting', models.BooleanField()),
                ('bachelors_granting_evidence', models.CharField(max_length=200)),
                ('source_locator', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['ipeds_unitid'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('publisher', models.CharField(max_length=200)),
                ('source_type', models.CharField(max_length=100)),
                ('data_year', models.CharField(max_length=20)),
                ('retrieved_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('extraction_method', models.CharField(default='csv_import', max_length=100)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='SeedInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=2)),
                ('expected_ownership', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ambiguous', 'Ambiguous'), ('unresolved', 'Unresolved')], default='pending', max_length=16)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_entries', to='catalog.institution')),
            ],
            options={
                'ordering': ['seed_order'],
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='catalog.sourcedocument'),
        ),
        migrations.CreateModel(
            name='InstitutionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=300)),
                ('alias_type', models.CharField(default='seed_name', max_length=40)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.institution')),
            ],
            options={
                'ordering': ['institution__ipeds_unitid', 'alias'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'alias', 'alias_type'), name='unique_institution_alias')],
            },
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('ambiguous_match', 'Ambiguous Match'), ('unresolved_match', 'Unresolved Match'), ('state_mismatch', 'State Mismatch'), ('ownership_mismatch', 'Ownership Mismatch'), ('duplicate_unitid', 'Duplicate Unitid')], max_length=32)),
                ('detail', models.TextField()),
                ('seed_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='catalog.seedinstitution')),
            ],
            options={
                'ordering': ['seed_entry__seed_order', 'issue_type'],
                'constraints': [models.UniqueConstraint(fields=('seed_entry', 'issue_type'), name='unique_seed_issue_type')],
            },
        ),
    ]
