# Generated by Django 5.2.17 on 2026-09-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataissue',
            name='issue_type',
            field=models.CharField(choices=[('ambiguous_match', 'Ambiguous Match'), ('unresolved_match', 'Unresolved Match'), ('state_mismatch', 'State Mismatch'), ('ownership_mismatch', 'Ownership Mismatch'), ('duplicate_unitid', 'Duplicate Unitid'), ('invalid_program_record', 'Invalid Program Record'), ('zero_bachelor_programs', 'Zero Bachelor Programs')], max_length=32),
        ),
        migrations.CreateModel(
            name='ProgramOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip_code', models.CharField(max_length=7)),
                ('cip_title', models.CharField(max_length=300)),
                ('credential_level', models.CharField(max_length=40)),
                ('award_level', models.PositiveSmallIntegerField()),
                ('program_name', models.CharField(blank=True, max_length=300)),
                ('completion_count', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=32)),
                ('academic_year', models.CharField(max_length=20)),
                ('source_locator', models.CharField(max_length=300)),
                ('evidence', models.TextField()),
                ('cip_title_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cip_titled_program_offerings', to='catalog.sourcedocument')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_offerings', to='catalog.institution')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_offerings', to='catalog.sourcedocument')),
            ],
            options={
                'ordering': ['institution__ipeds_unitid', 'cip_code'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'cip_code', 'credential_level', 'academic_year'), name='unique_program_offering_coverage')],
            },
        ),
    ]
