# Generated by Django 5.2.17 on 2026-09-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_dataissue_issue_type_programoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataissue',
            name='issue_type',
            field=models.CharField(choices=[('ambiguous_match', 'Ambiguous Match'), ('unresolved_match', 'Unresolved Match'), ('state_mismatch', 'State Mismatch'), ('ownership_mismatch', 'Ownership Mismatch'), ('duplicate_unitid', 'Duplicate Unitid'), ('invalid_program_record', 'Invalid Program Record'), ('zero_bachelor_programs', 'Zero Bachelor Programs'), ('invalid_admissions_record', 'Invalid Admissions Record')], max_length=32),
        ),
        migrations.CreateModel(
            name='AdmissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.CharField(max_length=20)),
                ('term', models.CharField(default='fall', max_length=20)),
                ('applicant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('admitted_count', models.PositiveIntegerField(blank=True, null=True)),
                ('enrolled_count', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sat_ebrw_25', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sat_ebrw_75', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sat_math_25', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sat_math_75', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('act_composite_25', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('act_composite_75', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sat_submission_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sat_submission_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('act_submission_count', models.PositiveIntegerField(blank=True, null=True)),
                ('act_submission_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('admissions_data_status', models.CharField(max_length=32)),
                ('sat_data_status', models.CharField(max_length=32)),
                ('act_data_status', models.CharField(max_length=32)),
                ('test_data_status', models.CharField(max_length=32)),
                ('source_flags', models.JSONField(default=dict)),
                ('source_locator', models.CharField(max_length=200)),
                ('evidence', models.TextField()),
                ('dictionary_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_dictionary_snapshots', to='catalog.sourcedocument')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_snapshots', to='catalog.institution')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_snapshots', to='catalog.sourcedocument')),
            ],
            options={
                'ordering': ['institution__ipeds_unitid', 'data_year', 'term'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'data_year', 'term'), name='unique_admission_snapshot_term')],
            },
        ),
    ]
