# Generated by Django 5.2.17 on 2026-09-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_dataissue_issue_type_admissionsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_scope', models.CharField(default='international_undergraduate', max_length=64)),
                ('test_type', models.CharField(choices=[('ielts', 'Ielts'), ('toefl_ibt', 'Toefl Ibt'), ('duolingo_english_test', 'Duolingo English Test')], max_length=32)),
                ('minimum_overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subscore_requirements', models.JSONField(default=dict)),
                ('waiver_text', models.TextField(blank=True)),
                ('conditional_text', models.TextField(blank=True)),
                ('policy_cycle', models.CharField(default='unspecified', max_length=100)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('not_found', 'Not Found'), ('not_required', 'Not Required'), ('conflicting', 'Conflicting'), ('unverified', 'Unverified'), ('extraction_failed', 'Extraction Failed')], max_length=32)),
                ('evidence', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['institution__ipeds_unitid', 'test_type', 'policy_cycle'],
            },
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='catalog.institution'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='page_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataissue',
            name='issue_type',
            field=models.CharField(choices=[('ambiguous_match', 'Ambiguous Match'), ('unresolved_match', 'Unresolved Match'), ('state_mismatch', 'State Mismatch'), ('ownership_mismatch', 'Ownership Mismatch'), ('duplicate_unitid', 'Duplicate Unitid'), ('invalid_program_record', 'Invalid Program Record'), ('zero_bachelor_programs', 'Zero Bachelor Programs'), ('invalid_admissions_record', 'Invalid Admissions Record'), ('source_fetch_failed', 'Source Fetch Failed'), ('english_extraction_review', 'English Extraction Review')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('institution', 'url'), name='unique_institution_source_url'),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_requirements', to='catalog.institution'),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='english_requirements', to='catalog.sourcedocument'),
        ),
        migrations.AddConstraint(
            model_name='englishrequirement',
            constraint=models.UniqueConstraint(fields=('institution', 'test_type', 'applicant_scope', 'policy_cycle'), name='unique_english_requirement_scope'),
        ),
    ]
