# Generated by Django 5.2.17 on 2026-09-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_englishrequirement_sourcedocument_canonical_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dataissue',
            name='unique_seed_issue_type',
        ),
        migrations.RemoveConstraint(
            model_name='englishrequirement',
            name='unique_english_requirement_scope',
        ),
        migrations.AddField(
            model_name='dataissue',
            name='issue_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='score_scale',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='valid_for_tests_before',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='englishrequirement',
            name='valid_for_tests_on_or_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='englishrequirement',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('no_minimum_published', 'No Minimum Published'), ('not_found', 'Not Found'), ('not_required', 'Not Required'), ('conflicting', 'Conflicting'), ('unverified', 'Unverified'), ('extraction_failed', 'Extraction Failed')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='dataissue',
            constraint=models.UniqueConstraint(fields=('seed_entry', 'issue_type', 'issue_key'), name='unique_seed_issue_type_key'),
        ),
        migrations.AddConstraint(
            model_name='englishrequirement',
            constraint=models.UniqueConstraint(fields=('institution', 'test_type', 'applicant_scope', 'policy_cycle', 'source', 'score_scale', 'valid_for_tests_before', 'valid_for_tests_on_or_after'), name='unique_english_requirement_version'),
        ),
    ]
