# Generated by Django 5.2.17 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_task_004_fix_english_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishrequirement",
            name="source_content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
