# Generated by Django 5.2.17 on 2026-09-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('citizenship_country_code', models.CharField(max_length=2)),
                ('residence_country_code', models.CharField(blank=True, max_length=2)),
                ('school_country_code', models.CharField(blank=True, max_length=2)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gpa_value', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('gpa_scale', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('gpa_weighting', models.CharField(choices=[('weighted', 'Weighted'), ('unweighted', 'Unweighted'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('class_size', models.PositiveIntegerField(blank=True, null=True)),
                ('study_mode', models.CharField(choices=[('known_major', 'Known Major'), ('explore', 'Explore')], max_length=16)),
                ('intended_cip_codes', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('annual_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('needs_financial_aid', models.BooleanField(blank=True, null=True)),
                ('preferred_states', models.JSONField(default=list)),
                ('excluded_states', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['profile_key'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('test_type', models.CharField(choices=[('sat', 'Sat'), ('act', 'Act'), ('ielts', 'Ielts'), ('toefl', 'Toefl'), ('duolingo', 'Duolingo')], max_length=12)),
                ('scale', models.CharField(max_length=24)),
                ('score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='applicants.applicantprofile')),
            ],
            options={
                'ordering': ['profile__profile_key', 'position'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'position'), name='unique_applicant_test_position')],
            },
        ),
    ]
